

//test file //120235456

### GET REQUEST 
GET http://localhost:8080/api/data/Posts

### POST REQUEST COLLECTION
POST http://localhost:8080/api/data/collection/test

### DELETE REQUEST COLLECTION
DELETE http://localhost:8080/api/data/collection/test

### PUT REQUEST 
PUT http://localhost:8080/api/data/Posts

{
        "album": "Rest Test",
        "artist": "Rest Test",
        "comments": [],
        "id": 847292,
        "rating": "8",
        "review": "Rest Test",
        "song": null,
        "timestamp": "9:29 PM - 10 Mar 23",
        "title": "Rest Test",
        "username": "restTest1"
    }

### DELETE REQUEST
DELETE http://localhost:8080/api/data/Posts
content-type: application/json

{
    "id":847292
}

