

//test file //120235456

### GET REQUEST 
GET http://localhost:8080/api/data/Posts

### POST REQUEST COLLECTION
POST http://localhost:8080/api/data/collection/test

### DELETE REQUEST COLLECTION
DELETE http://localhost:8080/api/data/collection/test

### PUT REQUEST 
PUT http://localhost:8080/api/data/Posts/-1/post
content-type: application/json

{
    "username":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NDVmMTY1YzA3ZmUwZDVlYTQ2ZjNkZiIsImlhdCI6MTY4MjMwNTM4NCwiZXhwIjoxNzY4NzA1Mzg0fQ._gH6C--DIbzmkfhEfgevGqxAF_NeUktcoFSpyTaQD_M",
    "artist":"f",
    "album":"fd",
    "song":"d",
    "rating":"2",
    "title":"3",
    "review":"2",
    "timestamp":"11:44 PM - 23 Apr 23",
    "id":662080,
    "comments":[]
}

### DELETE REQUEST
DELETE http://localhost:8080/api/data/Posts/
content-type: application/json

{
    "id":662080
}

